### PR TITLE
Delete sensitive data from log

### PR DESCRIPTION
**Pull request by shulkaolka**
Iteration 3 for the deletion of sensitive data from logs.
Please, review carefully.
Questions:
1.In case like [this](https://github.com/elasticio/sailor-nodejs/blob/master/lib/amqp.js#L79-L82): can `e` contain sensitive data? Is `deliveryTag` sensitive data or just service-data?
2. In [this](https://github.com/elasticio/sailor-nodejs/blob/master/lib/executor.js#L23) case: does it mean that all errors thrown by components always logged?
3. Is [there](https://github.com/elasticio/sailor-nodejs/blob/master/lib/sailor.js#L125) sensitive data in the `result`?
4. Is [there](https://github.com/elasticio/sailor-nodejs/blob/master/lib/sailor.js#L292) sensitive data in the `object`?

### CODE REVIEW

**Review by drobiazko — APPROVED** [review]

**Comment by drobiazko** [comment]
@shulkaolka 

1. I can't logging errors is ok
2. same as 1.
3. good catch. let's remove the logging of `result`
4. also should be removed

**Review by irisked — CHANGES_REQUESTED** [review]
1. its ok, nothing personal in deliveryTag
2. yes

3-4 Please change it to something meaningful and simply remove `result` or `object` logging.

**Comment by shulkaolka** [comment]
3-4 - fixed
about 1 - my suggestion is to delete this log statement (sometimes an error can contain some sensitive data - as an example, error from axios contains full request/response in error body). Do you agree? Or just leave as is?

**Comment by irisked** [comment]
> 3-4 - fixed
> about 1 - my suggestion is to delete this log statement (sometimes an error can contain some sensitive data - as an example, error from axios contains full request/response in error body). Do you agree? Or just leave as is?

I think there should be no sensitive data in that error.  Because it's fired when message can't be decrypted. Also, there is one more error logger down the stack [here](https://github.com/elasticio/sailor-nodejs/blob/ce9d42a28d22d00a3920c455b2bc4cb81fbcaaa4/lib/encryptor.js#L76) and [here](https://github.com/elasticio/sailor-nodejs/blob/ce9d42a28d22d00a3920c455b2bc4cb81fbcaaa4/lib/encryptor.js#L77) is actually the error that should be caught and logged at `1`.

So, it's pretty safe to just leave it as it is.

**Review by irisked — APPROVED** [review]

**Pull request merged**
