### PR TITLE
v3.0.0

### PR DESCRIPTION
**Pull request by ghaiklor**
- A lot of syntax fixes, eslint
- A lot of tech debt were removed, dependencies upgraded to the latest version
- Fixing failing tests that were failing silently
- Something else, do not remember, but minor

### CODE REVIEW

**Comment by jhorbulyk** [comment]
A couple high level questions:
* Why the jump to v3?  Is it because significant parts were refactored?
* Does this just solve the O(n^2) memory consumtion for incoming messages or were other issues addressed?
* What was causing the high memory consumption?
* Can you give a summary of items updated?

**Comment by ghaiklor** [comment]
> Why the jump to v3? Is it because significant parts were refactored?

Because we are losing the possibility to run it on older Node.js versions. e.g. your component written with sailor 2.x can be run in Node.js 4.x i.e., but with update to 3.x it is not possible.

> Does this just solve the O(n^2) memory consumtion for incoming messages or were other issues addressed?

There are other issues addressed as well, the most significant:

- Paying out tech debt, co/Q/bluebirds/generators with `yield` were removed and replaced with async/await syntax;
- A lot of Jasmine tests were failing silently without any errors - these are fixed as well;

> What was causing the high memory consumption?

Honestly, synthetic tests were the reason. All of the test cases with high memory consumption were reproduced by using `Buffer` instances. Make a long story short, when sailor is encrypting the message, it calls `JSON.stringify` on a Buffer, which returns string representation of it. And, of course, if you have a buffer representation of SMI = 2 i.e., it consumes 1 byte, but when you are getting string representation of it, it is string 2, not the SMI, leading to 8 bytes.

I made a test cases with more real examples and captured another snapshots to compare. By real example I mean a huge JSON structure, which has a size of 20 Mb. This structure was sent through sailor back and forth, while capturing snapshots. Comparison showed that there are no leaks at all in this case. Moreover, memory were cleaned so perfect that the size delta of consumed memory was negative.

> Can you give a summary of items updated?

- A lot of syntax fixes, eslint
- A lot of tech debt were removed, dependencies upgraded to the latest version
- Fixing failing tests that were failing silently
- Something else, do not remember, but minor

**Comment by zubairov** [comment]
Hm.... many changes with no obvious benefit. Why introduce new bugs?

**Comment by ghaiklor** [comment]
In case, technical debt and failing tests (_which are not protecting you from new bugs_) are not the reason, you can close the pull request.

Regard to memory issues, the only case when memory is growing - using Buffers, when passing payload to encryption. Because string representation of a buffer takes a lot more memory that buffer itself.

**Comment by ghaiklor** [comment]
@jhorbulyk I made a demonstration that shows "leaking" in case of sailor. Though, it is not a leak, but expected behaviour. I tried to explain the reasons behind it above - tl;dr string representation, feel free to ask more technical questions if you are interested.

Here is the demo that shows the "leaking" - https://repl.it/@ghaiklor/LinedCompetentCoderesource

**Pull request closed without merging**
