### PR TITLE
#1095 retry step data request

### PR DESCRIPTION
**Pull request by zuker**

### CODE REVIEW

**Comment by yarikos** [comment]
Why not implement this workaround on RestAPI lib?

**Comment by jhorbulyk** [comment]
@yarikos Which library?

**Comment by yarikos** [comment]
@jhorbulyk implement `retry logic` in `RestApiClient`.
Thereby this will be hidden from `sailor`'s point of view. Sailor  just call `apiClient.tasks.retrieveStep` and doesn't know how many actual http requests were made by `apiClient`.

**Comment by jhorbulyk** [comment]
Is this PR supposed to be a quick fix for https://github.com/elasticio/platform/issues/592 **or** *A failed request from the Sailor to the e.io REST API* from https://github.com/elasticio/platform/issues/509 **or** both?

**Comment by zuker** [comment]
@jhorbulyk this workaround for both

**Pull request merged**
